<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FinancialTransfers.RiskEngine-7b025627-47ea-4d70-8e58-e1e512e25fc5</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.13.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinancialTransfers.Application\FinancialTransfers.Application.csproj" />
    <ProjectReference Include="..\FinancialTransfers.Domain\FinancialTransfers.Domain.csproj" />
    <ProjectReference Include="..\FinancialTransfers.Infraestructure\FinancialTransfers.Infraestructure.csproj" />
  </ItemGroup>
</Project>
